name: debunk
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:

  args: ^2.3.1
  dcli: ^1.35.4
  http: ^0.13.5
  mason: ^0.1.0-dev.34

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

executables:
  debunk: debunk
